repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.2'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: true
    -   id: poetry-install

# -   repo: local
#     hooks:
#       - id: pylint
#         name: pylint
#         entry: pylint
#         language: system
#         types: [python]
#         args:
#           [
#             "-rn", # Only display messages
#             "-sn", # Don't display the score
#             "--rcfile=./project/.pylintrc", # Link to your config file
#             "--load-plugins=pylint.extensions.docparams,pylint_pydantic", # Load an extension
#           ]