apiVersion: v1
kind: Pod
metadata:
  name: fastapi-tdd-podman

spec:

  volumes:
    - hostPath:
        path: ./project
        type: Directory
      name: app-src

  containers:
    - name: web
      image: fastapi-summary
      ports:
      - containerPort: 8000
        hostPort: 8004
      volumeMounts:
      - mountPath: /usr/src/app:Z
        name: app-src
      env:
        - name: ENVIRONMENT
          value: dev
        - name: TESTING
          value: 0
      command: ["uvicorn", "app.main:app", "--reload", "--workers", "1", "--host", "0.0.0.0", "--port", "8000"]